/* src/lib/ed25519.c -- Ed25519 verification.  IMPORTED CODE.  NOT rlxfw's own.
 *
 *   upstream   TweetNaCl 20140427, https://tweetnacl.cr.yp.to/20140427/tweetnacl.c
 *   sha256     02e65bc3013ff2168983365e55906bc783c4c7e0a60d8100f17bb303a17175c4
 *   authors    Daniel J. Bernstein, Bernard van Gastel, Wesley Janssen,
 *              Tanja Lange, Peter Schwabe, Sjaak Smetsers
 *   licence    public domain
 *
 * GENERATED by src/rlxboot/test/mk-import.sh.  DO NOT EDIT.  Every line
 * between an IMPORTED marker pair is copied out of the upstream file by line
 * range; `check-import.sh` fails if one byte differs.  Retained ranges are
 * 5-9, 15-17, 19-23, 54-59, 66-69, 267-392, 588-654, 675-709, 743-777 and --
 * only under ED25519_SIGN, which the rlxboot payload never defines -- 711-741.
 *
 * WHAT IS rlxfw's OWN IN THIS FILE, and it is only this: `rlx_ed25519_verify`,
 * `rlx_ed25519_pubkey_from_seed`, `rlx_ed25519_sign` and the little-endian
 * `s < L` test they use.  They sit below the last IMPORTED marker, each
 * labelled.  The field arithmetic, the point arithmetic, the decompression and
 * the scalar reduction are upstream's and are described as upstream's
 * everywhere in this repository.
 *
 * WHY A WRAPPER RATHER THAN upstream's `crypto_sign_open`: that function copies
 * the whole signed message into a caller buffer and returns the message, which
 * a boot loader has no use for and which would put a variable-size buffer in
 * the trust path.  The wrapper hashes R || A || M out of one static buffer and
 * returns a verdict only.  It also adds the `s < L` test upstream omits.
 *
 * EXCLUSIONS -- deleted, never edited: salsa20, hsalsa20, poly1305, secretbox,
 * box, curve25519 (`crypto_scalarmult`, `_121665`, `_9`, `_0`), `ld32`,
 * `st32`, `L32`, `dl64`, `ts64`, `crypto_verify_16`, `randombytes`,
 * `crypto_box_keypair`, `crypto_sign_keypair` (it calls `randombytes`) and
 * `crypto_sign_open` (replaced by the wrapper).  SHA-512 lives in
 * `src/lib/sha512.c`, so `crypto_hash` is declared here and defined there --
 * that split is the one structural adaptation.
 */

#include "ed25519.h"
#include "sha512.h"

#define FOR(i,n) for (i = 0;i < n;++i)
#define sv static void

/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
typedef unsigned char u8;
typedef unsigned long u32;
typedef unsigned long long u64;
typedef long long i64;
typedef i64 gf[16];
/* ----- END IMPORTED ------------------------------------------------------ */
/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
static const gf
  gf0,
  gf1 = {1},
  D = {0x78a3, 0x1359, 0x4dca, 0x75eb, 0xd8ab, 0x4141, 0x0a4d, 0x0070, 0xe898, 0x7779, 0x4079, 0x8cc7, 0xfe73, 0x2b6f, 0x6cee, 0x5203},
  D2 = {0xf159, 0x26b2, 0x9b94, 0xebd6, 0xb156, 0x8283, 0x149a, 0x00e0, 0xd130, 0xeef3, 0x80f2, 0x198e, 0xfce7, 0x56df, 0xd9dc, 0x2406},
  X = {0xd51a, 0x8f25, 0x2d60, 0xc956, 0xa7b2, 0x9525, 0xc760, 0x692c, 0xdc5c, 0xfdd6, 0xe231, 0xc0a4, 0x53fe, 0xcd6e, 0x36d3, 0x2169},
  Y = {0x6658, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666},
  I = {0xa0b0, 0x4a0e, 0x1b27, 0xc4ee, 0xe478, 0xad2f, 0x1806, 0x2f43, 0xd7a7, 0x3dfb, 0x0099, 0x2b4d, 0xdf0b, 0x4fc1, 0x2480, 0x2b83};
/* ----- END IMPORTED ------------------------------------------------------ */
/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
static int vn(const u8 *x,const u8 *y,int n)
{
  u32 i,d = 0;
  FOR(i,n) d |= x[i]^y[i];
  return (1 & ((d - 1) >> 8)) - 1;
}
int crypto_verify_32(const u8 *x,const u8 *y)
{
  return vn(x,y,32);
}
sv set25519(gf r, const gf a)
{
  int i;
  FOR(i,16) r[i]=a[i];
}

sv car25519(gf o)
{
  int i;
  i64 c;
  FOR(i,16) {
    o[i]+=(1LL<<16);
    c=o[i]>>16;
    o[(i+1)*(i<15)]+=c-1+37*(c-1)*(i==15);
    o[i]-=c<<16;
  }
}

sv sel25519(gf p,gf q,int b)
{
  i64 t,i,c=~(b-1);
  FOR(i,16) {
    t= c&(p[i]^q[i]);
    p[i]^=t;
    q[i]^=t;
  }
}

sv pack25519(u8 *o,const gf n)
{
  int i,j,b;
  gf m,t;
  FOR(i,16) t[i]=n[i];
  car25519(t);
  car25519(t);
  car25519(t);
  FOR(j,2) {
    m[0]=t[0]-0xffed;
    for(i=1;i<15;i++) {
      m[i]=t[i]-0xffff-((m[i-1]>>16)&1);
      m[i-1]&=0xffff;
    }
    m[15]=t[15]-0x7fff-((m[14]>>16)&1);
    b=(m[15]>>16)&1;
    m[14]&=0xffff;
    sel25519(t,m,1-b);
  }
  FOR(i,16) {
    o[2*i]=t[i]&0xff;
    o[2*i+1]=t[i]>>8;
  }
}

static int neq25519(const gf a, const gf b)
{
  u8 c[32],d[32];
  pack25519(c,a);
  pack25519(d,b);
  return crypto_verify_32(c,d);
}

static u8 par25519(const gf a)
{
  u8 d[32];
  pack25519(d,a);
  return d[0]&1;
}

sv unpack25519(gf o, const u8 *n)
{
  int i;
  FOR(i,16) o[i]=n[2*i]+((i64)n[2*i+1]<<8);
  o[15]&=0x7fff;
}

sv A(gf o,const gf a,const gf b)
{
  int i;
  FOR(i,16) o[i]=a[i]+b[i];
}

sv Z(gf o,const gf a,const gf b)
{
  int i;
  FOR(i,16) o[i]=a[i]-b[i];
}

sv M(gf o,const gf a,const gf b)
{
  i64 i,j,t[31];
  FOR(i,31) t[i]=0;
  FOR(i,16) FOR(j,16) t[i+j]+=a[i]*b[j];
  FOR(i,15) t[i]+=38*t[i+16];
  FOR(i,16) o[i]=t[i];
  car25519(o);
  car25519(o);
}

sv S(gf o,const gf a)
{
  M(o,a,a);
}

sv inv25519(gf o,const gf i)
{
  gf c;
  int a;
  FOR(a,16) c[a]=i[a];
  for(a=253;a>=0;a--) {
    S(c,c);
    if(a!=2&&a!=4) M(c,c,i);
  }
  FOR(a,16) o[a]=c[a];
}

sv pow2523(gf o,const gf i)
{
  gf c;
  int a;
  FOR(a,16) c[a]=i[a];
  for(a=250;a>=0;a--) {
    S(c,c);
    if(a!=1) M(c,c,i);
  }
  FOR(a,16) o[a]=c[a];
}
sv add(gf p[4],gf q[4])
{
  gf a,b,c,d,t,e,f,g,h;
  
  Z(a, p[1], p[0]);
  Z(t, q[1], q[0]);
  M(a, a, t);
  A(b, p[0], p[1]);
  A(t, q[0], q[1]);
  M(b, b, t);
  M(c, p[3], q[3]);
  M(c, c, D2);
  M(d, p[2], q[2]);
  A(d, d, d);
  Z(e, b, a);
  Z(f, d, c);
  A(g, d, c);
  A(h, b, a);

  M(p[0], e, f);
  M(p[1], h, g);
  M(p[2], g, f);
  M(p[3], e, h);
}

sv cswap(gf p[4],gf q[4],u8 b)
{
  int i;
  FOR(i,4)
    sel25519(p[i],q[i],b);
}

sv pack(u8 *r,gf p[4])
{
  gf tx, ty, zi;
  inv25519(zi, p[2]); 
  M(tx, p[0], zi);
  M(ty, p[1], zi);
  pack25519(r, ty);
  r[31] ^= par25519(tx) << 7;
}

sv scalarmult(gf p[4],gf q[4],const u8 *s)
{
  int i;
  set25519(p[0],gf0);
  set25519(p[1],gf1);
  set25519(p[2],gf1);
  set25519(p[3],gf0);
  for (i = 255;i >= 0;--i) {
    u8 b = (s[i/8]>>(i&7))&1;
    cswap(p,q,b);
    add(q,p);
    add(p,p);
    cswap(p,q,b);
  }
}

sv scalarbase(gf p[4],const u8 *s)
{
  gf q[4];
  set25519(q[0],X);
  set25519(q[1],Y);
  set25519(q[2],gf1);
  M(q[3],X,Y);
  scalarmult(p,q,s);
}
static const u64 L[32] = {0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10};

sv modL(u8 *r,i64 x[64])
{
  i64 carry,i,j;
  for (i = 63;i >= 32;--i) {
    carry = 0;
    for (j = i - 32;j < i - 12;++j) {
      x[j] += carry - 16 * x[i] * L[j - (i - 32)];
      carry = (x[j] + 128) >> 8;
      x[j] -= carry << 8;
    }
    x[j] += carry;
    x[i] = 0;
  }
  carry = 0;
  FOR(j,32) {
    x[j] += carry - (x[31] >> 4) * L[j];
    carry = x[j] >> 8;
    x[j] &= 255;
  }
  FOR(j,32) x[j] -= carry * L[j];
  FOR(i,32) {
    x[i+1] += x[i] >> 8;
    r[i] = x[i] & 255;
  }
}

sv reduce(u8 *r)
{
  i64 x[64],i;
  FOR(i,64) x[i] = (u64) r[i];
  FOR(i,64) r[i] = 0;
  modL(r,x);
}
static int unpackneg(gf r[4],const u8 p[32])
{
  gf t, chk, num, den, den2, den4, den6;
  set25519(r[2],gf1);
  unpack25519(r[1],p);
  S(num,r[1]);
  M(den,num,D);
  Z(num,num,r[2]);
  A(den,r[2],den);

  S(den2,den);
  S(den4,den2);
  M(den6,den4,den2);
  M(t,den6,num);
  M(t,t,den);

  pow2523(t,t);
  M(t,t,num);
  M(t,t,den);
  M(t,t,den);
  M(r[0],t,den);

  S(chk,r[0]);
  M(chk,chk,den);
  if (neq25519(chk, num)) M(r[0],r[0],I);

  S(chk,r[0]);
  M(chk,chk,den);
  if (neq25519(chk, num)) return -1;

  if (par25519(r[0]) == (p[31]>>7)) Z(r[0],gf0,r[0]);

  M(r[3],r[0],r[1]);
  return 0;
}
/* ----- END IMPORTED ------------------------------------------------------ */

#ifdef ED25519_SIGN
/* Signing is built for the HOST TEST FIXTURES ONLY.  The rlxboot payload
 * defines neither ED25519_SIGN nor ED25519_KEYGEN, so a reader can confirm
 * from `nm` that the device image contains no signer. */
/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
int crypto_sign(u8 *sm,u64 *smlen,const u8 *m,u64 n,const u8 *sk)
{
  u8 d[64],h[64],r[64];
  i64 i,j,x[64];
  gf p[4];

  crypto_hash(d, sk, 32);
  d[0] &= 248;
  d[31] &= 127;
  d[31] |= 64;

  *smlen = n+64;
  FOR(i,n) sm[64 + i] = m[i];
  FOR(i,32) sm[32 + i] = d[32 + i];

  crypto_hash(r, sm+32, n+32);
  reduce(r);
  scalarbase(p,r);
  pack(sm,p);

  FOR(i,32) sm[i+32] = sk[i+32];
  crypto_hash(h,sm,n + 64);
  reduce(h);

  FOR(i,64) x[i] = 0;
  FOR(i,32) x[i] = (u64) r[i];
  FOR(i,32) FOR(j,32) x[i+j] += h[i] * (u64) d[j];
  modL(sm + 32,x);

  return 0;
}
/* ----- END IMPORTED ------------------------------------------------------ */
#endif /* ED25519_SIGN */

/* =========================================================================
 * rlxfw's own code starts here.  Nothing above this line is rlxfw's.
 * ========================================================================= */

/* The group order L, little-endian, as bytes.  Same number as the imported
 * `L[32]` above; a second spelling because that one is `u64[32]` and this test
 * wants bytes.  It is a published constant of the curve, not code. */
static const u8 rlx_L_bytes[32] = {
	0xed,0xd3,0xf5,0x5c,0x1a,0x63,0x12,0x58,
	0xd6,0x9c,0xf7,0xa2,0xde,0xf9,0xde,0x14,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x10
};

/* s < L, on a 32-byte little-endian s.  RFC 8032 s5.1.7 requires a verifier to
 * reject an s that is not reduced; upstream's `crypto_sign_open` does not, so
 * a signature with s + L in place of s verifies there.  That is malleability,
 * not forgery -- it needs a valid signature to start from -- but a loader that
 * accepts two byte strings for one authorisation is a loader whose "one
 * container, one signature" claim is false, so the test is here.
 *
 * Branch-free and constant-time in s: it is a public value, but writing the
 * comparison this way costs nothing and removes the question. */
static int rlx_s_below_L(const u8 *s)
{
	int i;
	u32 borrow = 0, lt = 0, gt = 0, d;
	for (i = 31; i >= 0; i--) {
		d = (u32)s[i] ^ (u32)rlx_L_bytes[i];
		/* first difference from the top decides; later ones cannot */
		gt |= (~lt & ~gt) & (d ? ((u32)s[i] > (u32)rlx_L_bytes[i] ? 1u : 0u) : 0u);
		lt |= (~lt & ~gt) & (d ? ((u32)s[i] < (u32)rlx_L_bytes[i] ? 1u : 0u) : 0u);
	}
	(void)borrow;
	return (int)(lt & 1u);
}

/* The one static buffer the verifier needs: R (32) || A (32) || M.
 * No malloc, no VLA, no recursion.  ED25519_MSG_MAX bounds M and is a
 * compile-time constant; a longer message is refused, it is not truncated. */
static u8 rlx_hbuf[64 + ED25519_MSG_MAX];

int rlx_ed25519_verify(const unsigned char *sig, const unsigned char *msg,
                       unsigned long msglen, const unsigned char *pk)
{
	u8 h[64], t[32];
	gf p[4], q[4];
	unsigned long i;

	if (msglen > ED25519_MSG_MAX)
		return RLX_ED25519_ETOOLONG;
	if (!rlx_s_below_L(sig + 32))
		return RLX_ED25519_ESCALAR;
	if (unpackneg(q, pk))
		return RLX_ED25519_EPUBKEY;

	FOR(i,32) rlx_hbuf[i] = sig[i];
	FOR(i,32) rlx_hbuf[32 + i] = pk[i];
	FOR(i,msglen) rlx_hbuf[64 + i] = msg[i];

	crypto_hash(h, rlx_hbuf, (u64)(64 + msglen));
	reduce(h);
	scalarmult(p, q, h);

	scalarbase(q, sig + 32);
	add(p, q);
	pack(t, p);

	if (crypto_verify_32(sig, t))
		return RLX_ED25519_EBADSIG;
	return 0;
}

#ifdef ED25519_KEYGEN
/* Public key from a 32-byte seed, RFC 8032 s5.1.5.  HOST/TEST ONLY: the
 * rlxboot payload does not define ED25519_KEYGEN. */
int rlx_ed25519_pubkey_from_seed(unsigned char pk[32], const unsigned char seed[32])
{
	u8 d[64];
	gf p[4];

	crypto_hash(d, seed, 32);
	d[0] &= 248;
	d[31] &= 127;
	d[31] |= 64;
	scalarbase(p, d);
	pack(pk, p);
	return 0;
}
#endif /* ED25519_KEYGEN */

#ifdef ED25519_SIGN
/* Sign, for the host test fixtures.  `sk` is seed || pubkey, upstream's
 * layout.  HOST/TEST ONLY. */
int rlx_ed25519_sign(unsigned char sig[64], const unsigned char *msg,
                     unsigned long msglen, const unsigned char sk[64])
{
	static u8 sm[64 + ED25519_MSG_MAX];
	u64 smlen = 0;
	unsigned long i;

	if (msglen > ED25519_MSG_MAX)
		return RLX_ED25519_ETOOLONG;
	crypto_sign(sm, &smlen, msg, (u64)msglen, sk);
	FOR(i,64) sig[i] = sm[i];
	return 0;
}
#endif /* ED25519_SIGN */
