/* prodkey.h -- the update key a KEY=prod rlxboot trusts: the PUBLIC half of
 * the owner's production key (the R8b spec's D15).
 * GENERATED by src/rlxboot/mkprodkey.py -- do not edit; run it again.
 *
 *   public key  4a6eda72ea11e75f0a3b695462744d09bc27b2d4ff2f95ab7037e045e1a3096e
 *
 * `mkprodkey.py check` reads this file before every KEY=prod build and
 * refuses unless the line above, RLXBOOT_PRODKEY_HEX and rlxboot_prodkey[]
 * hold the same 32 bytes, they are not the development key, and they
 * decode to a curve point of large order.  The seed this was derived from
 * is not in this repository and must never be (devkey.h).
 */
#ifndef RLXBOOT_PRODKEY_H
#define RLXBOOT_PRODKEY_H

#define RLXBOOT_PRODKEY_HEX \
	"4a6eda72ea11e75f0a3b695462744d09bc27b2d4ff2f95ab7037e045e1a3096e"

static const unsigned char rlxboot_prodkey[32] = {
	0x4a,0x6e,0xda,0x72,0xea,0x11,0xe7,0x5f,
	0x0a,0x3b,0x69,0x54,0x62,0x74,0x4d,0x09,
	0xbc,0x27,0xb2,0xd4,0xff,0x2f,0x95,0xab,
	0x70,0x37,0xe0,0x45,0xe1,0xa3,0x09,0x6e
};

#endif /* RLXBOOT_PRODKEY_H */
