/* prodkey.h -- the update key a KEY=prod rlxboot trusts: the PUBLIC half of
 * the owner's production key (the R8b spec's D15).
 * GENERATED by src/rlxboot/mkprodkey.py -- do not edit; run it again.
 *
 *   public key  NONE -- the production key has not been generated
 *
 * A KEY=prod build (the Makefile's default) REFUSES while this file holds
 * no key: `mkprodkey.py check` says so before anything is compiled, and
 * main.c stops at #error if the Makefile is bypassed.  When the owner's
 * public key arrives:
 *
 *   python3 src/rlxboot/mkprodkey.py write --pubkey <64 hex>
 *
 * A development image needs no key here: build it with KEY=dev.
 */
#ifndef RLXBOOT_PRODKEY_H
#define RLXBOOT_PRODKEY_H
#endif /* RLXBOOT_PRODKEY_H */
