#!/bin/sh
# mk-import.sh -- regenerate src/lib/sha512.c and src/lib/ed25519.c from the
# upstream TweetNaCl source, byte for byte.
#
# WHY THIS SCRIPT EXISTS.  `src/lib/ed25519.c` and `src/lib/sha512.c` are an
# IMPORT, not rlxfw code.  A header comment claiming "unmodified upstream" is an
# assertion; this script is the instrument.  Given the upstream file it rebuilds
# both committed files, and `check-import.sh` diffs the result against what is
# in the tree -- so an edit to one imported line is a test failure with a name,
# not a thing a reader has to notice.
#
#   upstream   https://tweetnacl.cr.yp.to/20140427/tweetnacl.c
#   sha256     02e65bc3013ff2168983365e55906bc783c4c7e0a60d8100f17bb303a17175c4
#   licence    public domain (TweetNaCl: Bernstein, Janssen, Lange, Schwabe)
#
# Usage:  mk-import.sh <upstream tweetnacl.c> <outdir>
# The upstream file is NOT committed: it is fetched, hashed, and consumed.
#
# Every retained region is named by upstream line range below.  Regions are
# copied with `sed -n`, so nothing in them can differ from upstream by a byte.
# What is NOT copied is as much a decision as what is: see EXCLUSIONS.

set -e

UP=${1:?usage: mk-import.sh <tweetnacl.c> <outdir>}
OUT=${2:?usage: mk-import.sh <tweetnacl.c> <outdir>}

WANT=02e65bc3013ff2168983365e55906bc783c4c7e0a60d8100f17bb303a17175c4
GOT=$(sha256sum "$UP" | cut -d' ' -f1)
if [ "$GOT" != "$WANT" ]; then
	echo "mk-import: $UP is sha256 $GOT, not the pinned $WANT" >&2
	exit 2
fi

mkdir -p "$OUT"

# ---------------------------------------------------------------------------
# sha512.c
# ---------------------------------------------------------------------------
# Retained upstream line ranges:
#    35- 40  dl64()          big-endian 8-byte load
#    48- 52  ts64()          big-endian 8-byte store
#   487-586  R Ch Maj Sigma0 Sigma1 sigma0 sigma1, K[80],
#            crypto_hashblocks(), iv[64], crypto_hash()
{
cat <<'EOF'
/* src/lib/sha512.c -- SHA-512.  IMPORTED CODE.  NOT rlxfw's own.
 *
 *   upstream   TweetNaCl 20140427, https://tweetnacl.cr.yp.to/20140427/tweetnacl.c
 *   sha256     02e65bc3013ff2168983365e55906bc783c4c7e0a60d8100f17bb303a17175c4
 *   authors    Daniel J. Bernstein, Bernard van Gastel, Wesley Janssen,
 *              Tanja Lange, Peter Schwabe, Sjaak Smetsers
 *   licence    public domain
 *
 * GENERATED by src/rlxboot/test/mk-import.sh.  DO NOT EDIT: the region between
 * the IMPORTED markers is copied out of the upstream file by line range and
 * `check-import.sh` fails if one byte of it differs.  Retained ranges are
 * 35-40 (dl64), 48-52 (ts64) and 487-586 (the whole SHA-512 implementation).
 *
 * The ONLY things outside those markers are (a) the typedefs and the two
 * macros upstream takes from `tweetnacl.h`, which this tree has no libc to
 * supply, and (b) `rlx_sha512`, an rlxfw wrapper -- rlxfw's own code, and
 * labelled as such.  Nothing inside the markers was altered, reordered or
 * reformatted.
 *
 * EXCLUSIONS -- deleted, never edited: salsa20, hsalsa20, poly1305,
 * secretbox, box, curve25519 (`crypto_scalarmult`), `randombytes` and the two
 * keypair generators.  `ld32`, `st32` and `L32` go with salsa20.
 */

typedef unsigned char u8;
typedef unsigned long long u64;
#define FOR(i,n) for (i = 0;i < n;++i)
#define sv static void

/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
EOF
sed -n '35,40p;48,52p;487,586p' "$UP"
cat <<'EOF'
/* ----- END IMPORTED ------------------------------------------------------ */

/* rlxfw's own, below this line. */
#include "sha512.h"

void rlx_sha512(unsigned char out[64], const unsigned char *m, unsigned long n)
{
	crypto_hash(out, m, (u64)n);
}
EOF
} > "$OUT/sha512.c"

# ---------------------------------------------------------------------------
# ed25519.c
# ---------------------------------------------------------------------------
# Retained upstream line ranges:
#     5-  9  the typedefs (u8 u32 u64 i64 gf)
#    15- 17, 19-23   the gf constants gf0 gf1 D D2 X Y I.  Line 18 is
#            `_121665`, which belongs to curve25519; excluding it is what keeps
#            `-Wunused-const-variable` quiet without editing a retained line.
#            The declaration stays one comma list and stays valid.
#    54- 59  vn()
#    66- 69  crypto_verify_32()
#   267-392  set25519 car25519 sel25519 pack25519 neq25519 par25519
#            unpack25519 A Z M S inv25519 pow2523
#   588-654  add cswap pack scalarmult scalarbase
#   675-709  L[32] modL reduce
#   743-777  unpackneg
#   711-741  crypto_sign            -- HOST TESTS ONLY, under ED25519_SIGN
{
cat <<'EOF'
/* src/lib/ed25519.c -- Ed25519 verification.  IMPORTED CODE.  NOT rlxfw's own.
 *
 *   upstream   TweetNaCl 20140427, https://tweetnacl.cr.yp.to/20140427/tweetnacl.c
 *   sha256     02e65bc3013ff2168983365e55906bc783c4c7e0a60d8100f17bb303a17175c4
 *   authors    Daniel J. Bernstein, Bernard van Gastel, Wesley Janssen,
 *              Tanja Lange, Peter Schwabe, Sjaak Smetsers
 *   licence    public domain
 *
 * GENERATED by src/rlxboot/test/mk-import.sh.  DO NOT EDIT.  Every line
 * between an IMPORTED marker pair is copied out of the upstream file by line
 * range; `check-import.sh` fails if one byte differs.  Retained ranges are
 * 5-9, 15-17, 19-23, 54-59, 66-69, 267-392, 588-654, 675-709, 743-777 and --
 * only under ED25519_SIGN, which the rlxboot payload never defines -- 711-741.
 *
 * WHAT IS rlxfw's OWN IN THIS FILE, and it is only this: `rlx_ed25519_verify`,
 * `rlx_ed25519_pubkey_from_seed`, `rlx_ed25519_sign` and the little-endian
 * `s < L` test they use.  They sit below the last IMPORTED marker, each
 * labelled.  The field arithmetic, the point arithmetic, the decompression and
 * the scalar reduction are upstream's and are described as upstream's
 * everywhere in this repository.
 *
 * WHY A WRAPPER RATHER THAN upstream's `crypto_sign_open`: that function copies
 * the whole signed message into a caller buffer and returns the message, which
 * a boot loader has no use for and which would put a variable-size buffer in
 * the trust path.  The wrapper hashes R || A || M out of one static buffer and
 * returns a verdict only.  It also adds the `s < L` test upstream omits.
 *
 * EXCLUSIONS -- deleted, never edited: salsa20, hsalsa20, poly1305, secretbox,
 * box, curve25519 (`crypto_scalarmult`, `_121665`, `_9`, `_0`), `ld32`,
 * `st32`, `L32`, `dl64`, `ts64`, `crypto_verify_16`, `randombytes`,
 * `crypto_box_keypair`, `crypto_sign_keypair` (it calls `randombytes`) and
 * `crypto_sign_open` (replaced by the wrapper).  SHA-512 lives in
 * `src/lib/sha512.c`, so `crypto_hash` is declared here and defined there --
 * that split is the one structural adaptation.
 */

#include "ed25519.h"
#include "sha512.h"

#define FOR(i,n) for (i = 0;i < n;++i)
#define sv static void

/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
EOF
sed -n '5,9p' "$UP"
cat <<'EOF'
/* ----- END IMPORTED ------------------------------------------------------ */
/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
EOF
sed -n '15,17p;19,23p' "$UP"
cat <<'EOF'
/* ----- END IMPORTED ------------------------------------------------------ */
/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
EOF
sed -n '54,59p;66,69p;267,392p;588,654p;675,709p;743,777p' "$UP"
cat <<'EOF'
/* ----- END IMPORTED ------------------------------------------------------ */

#ifdef ED25519_SIGN
/* Signing is built for the HOST TEST FIXTURES ONLY.  The rlxboot payload
 * defines neither ED25519_SIGN nor ED25519_KEYGEN, so a reader can confirm
 * from `nm` that the device image contains no signer. */
/* ----- BEGIN IMPORTED (TweetNaCl 20140427) ------------------------------- */
EOF
sed -n '711,741p' "$UP"
cat <<'EOF'
/* ----- END IMPORTED ------------------------------------------------------ */
#endif /* ED25519_SIGN */
EOF
cat <<'EOF'

/* =========================================================================
 * rlxfw's own code starts here.  Nothing above this line is rlxfw's.
 * ========================================================================= */

/* The group order L, little-endian, as bytes.  Same number as the imported
 * `L[32]` above; a second spelling because that one is `u64[32]` and this test
 * wants bytes.  It is a published constant of the curve, not code. */
static const u8 rlx_L_bytes[32] = {
	0xed,0xd3,0xf5,0x5c,0x1a,0x63,0x12,0x58,
	0xd6,0x9c,0xf7,0xa2,0xde,0xf9,0xde,0x14,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x10
};

/* s < L, on a 32-byte little-endian s.  RFC 8032 s5.1.7 requires a verifier to
 * reject an s that is not reduced; upstream's `crypto_sign_open` does not, so
 * a signature with s + L in place of s verifies there.  That is malleability,
 * not forgery -- it needs a valid signature to start from -- but a loader that
 * accepts two byte strings for one authorisation is a loader whose "one
 * container, one signature" claim is false, so the test is here.
 *
 * Branch-free and constant-time in s: it is a public value, but writing the
 * comparison this way costs nothing and removes the question. */
static int rlx_s_below_L(const u8 *s)
{
	int i;
	u32 borrow = 0, lt = 0, gt = 0, d;
	for (i = 31; i >= 0; i--) {
		d = (u32)s[i] ^ (u32)rlx_L_bytes[i];
		/* first difference from the top decides; later ones cannot */
		gt |= (~lt & ~gt) & (d ? ((u32)s[i] > (u32)rlx_L_bytes[i] ? 1u : 0u) : 0u);
		lt |= (~lt & ~gt) & (d ? ((u32)s[i] < (u32)rlx_L_bytes[i] ? 1u : 0u) : 0u);
	}
	(void)borrow;
	return (int)(lt & 1u);
}

/* The one static buffer the verifier needs: R (32) || A (32) || M.
 * No malloc, no VLA, no recursion.  ED25519_MSG_MAX bounds M and is a
 * compile-time constant; a longer message is refused, it is not truncated. */
static u8 rlx_hbuf[64 + ED25519_MSG_MAX];

int rlx_ed25519_verify(const unsigned char *sig, const unsigned char *msg,
                       unsigned long msglen, const unsigned char *pk)
{
	u8 h[64], t[32];
	gf p[4], q[4];
	unsigned long i;

	if (msglen > ED25519_MSG_MAX)
		return RLX_ED25519_ETOOLONG;
	if (!rlx_s_below_L(sig + 32))
		return RLX_ED25519_ESCALAR;
	if (unpackneg(q, pk))
		return RLX_ED25519_EPUBKEY;

	FOR(i,32) rlx_hbuf[i] = sig[i];
	FOR(i,32) rlx_hbuf[32 + i] = pk[i];
	FOR(i,msglen) rlx_hbuf[64 + i] = msg[i];

	crypto_hash(h, rlx_hbuf, (u64)(64 + msglen));
	reduce(h);
	scalarmult(p, q, h);

	scalarbase(q, sig + 32);
	add(p, q);
	pack(t, p);

	if (crypto_verify_32(sig, t))
		return RLX_ED25519_EBADSIG;
	return 0;
}

#ifdef ED25519_KEYGEN
/* Public key from a 32-byte seed, RFC 8032 s5.1.5.  HOST/TEST ONLY: the
 * rlxboot payload does not define ED25519_KEYGEN. */
int rlx_ed25519_pubkey_from_seed(unsigned char pk[32], const unsigned char seed[32])
{
	u8 d[64];
	gf p[4];

	crypto_hash(d, seed, 32);
	d[0] &= 248;
	d[31] &= 127;
	d[31] |= 64;
	scalarbase(p, d);
	pack(pk, p);
	return 0;
}
#endif /* ED25519_KEYGEN */

#ifdef ED25519_SIGN
/* Sign, for the host test fixtures.  `sk` is seed || pubkey, upstream's
 * layout.  HOST/TEST ONLY. */
int rlx_ed25519_sign(unsigned char sig[64], const unsigned char *msg,
                     unsigned long msglen, const unsigned char sk[64])
{
	static u8 sm[64 + ED25519_MSG_MAX];
	u64 smlen = 0;
	unsigned long i;

	if (msglen > ED25519_MSG_MAX)
		return RLX_ED25519_ETOOLONG;
	crypto_sign(sm, &smlen, msg, (u64)msglen, sk);
	FOR(i,64) sig[i] = sm[i];
	return 0;
}
#endif /* ED25519_SIGN */
EOF
} > "$OUT/ed25519.c"

echo "mk-import: wrote $OUT/sha512.c $OUT/ed25519.c"
