# probe6rows.mk -- GENERATED by tools/tcpay.py.  DO NOT EDIT.

P6_ROWS      := 12
RB_WORDS_probe6 := 129

FWRE_WORK    ?= /home/key/fwre-work
TCROOT       ?= $(FWRE_WORK)/rebuild/r2ab/tc
FRAG_CFLAGS  := -O2 -mabi=32 -msoft-float -EB -G0 -mno-abicalls -fno-pic

# 🔴 THE rsdk DRIVERS CANNOT READ A SOURCE FILE ON DrvFs, AND THIS IS A
# REFUSAL BECAUSE THE SYMPTOM POINTS AT THE WRONG THING.  量 2026-09-14,
# with the control beside it: `mips-linux-gcc` is a 32-bit i386 ELF, and
# `/mnt/c` hands it inode 49539595901085916 -- which does not fit a 32-bit
# `struct stat`, so `cc1` dies with
#
#     cc1: .../frag.c: Value too large for defined data type
#
# The SAME BYTES copied to ext4 compile to a 928-byte object.  The message
# names the source file and reads like a defect in it, which is why this
# is a named refusal and not a comment.  `CLAUDE.md`'s rule is *binaries
# and vendor source trees never live under /mnt/c*; this is its third face
# -- a vendor binary cannot READ a file there either.
ifeq ($(P),probe6)
ifneq ($(findstring /mnt/,$(abspath $(BUILD))),)
$(error probe6 needs BUILD= on a real Linux filesystem. $(abspath $(BUILD)) is DrvFs, and the 32-bit rsdk drivers cannot stat a file there -- `Value too large for defined data type`, which names frag.c and means the filesystem. Use BUILD=$(FWRE_WORK)/rebuild/<something>)
endif
endif

# And the fragment is compiled from a COPY inside $(OBJDIR) for the same
# reason: `$(HERE)frag.c` is in the repository, which is on DrvFs.  The
# copy is a prerequisite rather than a recipe step so that `make -n` still
# reports honestly, and `cp -p` keeps the mtime so the copy is not newer
# than its source on every build.
$(OBJDIR)/frag.c: $(HERE)frag.c | $(OBJDIR)
	cp -p $< $@

FRAGOBJS_probe6 := $(OBJDIR)/frag-v1.o $(OBJDIR)/frag-v2.o $(OBJDIR)/frag-v3.o $(OBJDIR)/frag-v4.o $(OBJDIR)/frag-v5.o $(OBJDIR)/frag-v6.o $(OBJDIR)/frag-v7.o $(OBJDIR)/frag-v8.o $(OBJDIR)/frag-v9.o $(OBJDIR)/frag-v10.o

# v1: host cross-compiler, gcc 12.4.0, binutils 2.42 -- the instrument, -march=mips1
P6_CC_v1 := mips-linux-gnu-gcc
$(OBJDIR)/frag-v1.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v1       mips-linux-gnu-gcc -march=mips1'
	$(P6_CC_v1) -march=mips1 $(FRAG_CFLAGS) -Drlxf=rlxf_v1 -c -o $@ $<

# v2: host cross-compiler, gcc 12.4.0, binutils 2.42 -- the instrument, -march=mips2
P6_CC_v2 := mips-linux-gnu-gcc
$(OBJDIR)/frag-v2.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v2       mips-linux-gnu-gcc -march=mips2'
	$(P6_CC_v2) -march=mips2 $(FRAG_CFLAGS) -Drlxf=rlxf_v2 -c -o $@ $<

# v3: host cross-compiler, gcc 12.4.0, binutils 2.42 -- the instrument, -march=mips32
P6_CC_v3 := mips-linux-gnu-gcc
$(OBJDIR)/frag-v3.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v3       mips-linux-gnu-gcc -march=mips32'
	$(P6_CC_v3) -march=mips32 $(FRAG_CFLAGS) -Drlxf=rlxf_v3 -c -o $@ $<

# v4: rsdk 1.3.6, gcc 3.4.6-1.3.6, binutils 2.16.94, 4181 release, -march=4181
P6_CC_v4 := $(TCROOT)/rsdk-1.3.6-4181-EB-2.6.30-0.9.30/bin/mips-linux-gcc
$(OBJDIR)/frag-v4.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v4       mips-linux-gcc -march=4181'
	$(P6_CC_v4) -march=4181 $(FRAG_CFLAGS) -Drlxf=rlxf_v4 -c -o $@ $<

# v5: rsdk 1.3.6, gcc 3.4.6-1.3.6, binutils 2.16.94, 4181 release, -march=5281
P6_CC_v5 := $(TCROOT)/rsdk-1.3.6-4181-EB-2.6.30-0.9.30/bin/mips-linux-gcc
$(OBJDIR)/frag-v5.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v5       mips-linux-gcc -march=5281'
	$(P6_CC_v5) -march=5281 $(FRAG_CFLAGS) -Drlxf=rlxf_v5 -c -o $@ $<

# v6: rsdk 1.3.6, gcc 3.4.6-1.3.6, binutils 2.16.94, 5281 release, -march=4181
P6_CC_v6 := $(TCROOT)/rsdk-1.3.6-5281-EB-2.6.30-0.9.30/bin/mips-linux-gcc
$(OBJDIR)/frag-v6.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v6       mips-linux-gcc -march=4181'
	$(P6_CC_v6) -march=4181 $(FRAG_CFLAGS) -Drlxf=rlxf_v6 -c -o $@ $<

# v7: rsdk 1.3.6, gcc 3.4.6-1.3.6, binutils 2.16.94, 5281 release, -march=5281
P6_CC_v7 := $(TCROOT)/rsdk-1.3.6-5281-EB-2.6.30-0.9.30/bin/mips-linux-gcc
$(OBJDIR)/frag-v7.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v7       mips-linux-gcc -march=5281'
	$(P6_CC_v7) -march=5281 $(FRAG_CFLAGS) -Drlxf=rlxf_v7 -c -o $@ $<

# v8: rsdk 1.5.5p4, gcc 4.4.5, binutils 2.19.92, 5281 release, -march=4181
P6_CC_v8 := $(TCROOT)/rsdk-1.5.5-5281-EB-2.6.30-0.9.30.3-110714/bin/mips-linux-xgcc
$(OBJDIR)/frag-v8.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v8       mips-linux-xgcc -march=4181'
	$(P6_CC_v8) -march=4181 $(FRAG_CFLAGS) -Drlxf=rlxf_v8 -c -o $@ $<

# v9: rsdk 1.5.5p4, gcc 4.4.5, binutils 2.19.92, 5281 release, -march=5281
P6_CC_v9 := $(TCROOT)/rsdk-1.5.5-5281-EB-2.6.30-0.9.30.3-110714/bin/mips-linux-xgcc
$(OBJDIR)/frag-v9.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v9       mips-linux-xgcc -march=5281'
	$(P6_CC_v9) -march=5281 $(FRAG_CFLAGS) -Drlxf=rlxf_v9 -c -o $@ $<

# v10: rsdk 1.5.5p4, gcc 4.4.5, binutils 2.19.92, 5281 release, -march=4281
P6_CC_v10 := $(TCROOT)/rsdk-1.5.5-5281-EB-2.6.30-0.9.30.3-110714/bin/mips-linux-xgcc
$(OBJDIR)/frag-v10.o: $(OBJDIR)/frag.c $(HERE)probe6rows.mk | $(OBJDIR)
	@echo '  FRAG   v10      mips-linux-xgcc -march=4281'
	$(P6_CC_v10) -march=4281 $(FRAG_CFLAGS) -Drlxf=rlxf_v10 -c -o $@ $<

