/* probe6rows.h -- GENERATED by tools/tcpay.py.  DO NOT EDIT. */
#ifndef RLXPROBE6_ROWS_H
#define RLXPROBE6_ROWS_H

#define P6_ROWS		12u
#define P6_ROW_WORDS	8u
#define P6_TAG_BASE	0x50060000u

#define P6_SRC_VAL	0xA5A5F00Du
#define P6_SENTINEL	0xB10CB10Cu
#define P6_DST_INIT	0x5A5A0FF2u

typedef void (*p6_thunk)(volatile unsigned *d,
			 volatile const unsigned *s, unsigned sent);

extern const char *const p6_names[P6_ROWS];
extern const p6_thunk p6_thunks[P6_ROWS];

#endif
