# probe4rows.mk -- GENERATED by tools/isapay.py from tools/isa-payload.tsv.
# DO NOT EDIT.  Included by tools/rlxprobe/Makefile.
#
# The result block's length is a FUNCTION of the row count, so it is emitted
# here rather than typed into the Makefile beside a second copy of the
# arithmetic.  probe0..probe3 each carry that second copy and
# `tools/test-rlxprobe.sh` exists partly to keep them honest; probe4 removes
# the class instead.  probe4.c re-derives the same number at compile time and
# refuses to build if it disagrees, so the two consumers still check each other.
P4_ROWS      := 75
RB_WORDS_probe4 := 633
