/* probe5rows.h -- GENERATED by tools/hazpay.py from tools/isa-hazard.tsv.
 * DO NOT EDIT.
 *
 * The expected constants are NOT here.  `probe5` records eight words per row
 * and `hazpay.py verdict` decides at the desk, so there is nothing in the image
 * for a wrong expectation to be silently right against.
 */
#ifndef PROBE5ROWS_H
#define PROBE5ROWS_H

#define P5_ROWS		24u
#define P5_ROW_WORDS	8u
#define P5_TAG_BASE	0x52350000u
#define P5_SCRATCH_B	48u

/* Byte offsets inside the scratch block.  Offset 12 holds `&mem0` and is
 * written by the payload in C: the `storebase` family loads a base address out
 * of memory, and a cell that STORED it there first would itself be the
 * store-producer shape `tools/isa-hazard.tsv` declares not measurable. */
#define P5_O_ADDR0	12u
#define P5_O_MEM0	16u

struct p5_row {
	void (*cell)(void *);
	u32 in_a;
	u32 in_b;
	u32 mem0;
	u32 mem1;
	u32 seed;
};

void rlx_p5_lu_alu_d0(void *);
void rlx_p5_lu_alu_d1(void *);
void rlx_p5_lu_alu_d2(void *);
void rlx_p5_lu_sd_d0(void *);
void rlx_p5_lu_sd_d1(void *);
void rlx_p5_sb_m0_d0(void *);
void rlx_p5_sb_m1_d0(void *);
void rlx_p5_sb_m0_d1(void *);
void rlx_p5_sb_m1_d1(void *);
void rlx_p5_hl_d0(void *);
void rlx_p5_hl_d1(void *);
void rlx_p5_hl_d2(void *);
void rlx_p5_hl_d3(void *);
void rlx_p5_c0_d0(void *);
void rlx_p5_c0_d1(void *);
void rlx_p5_c0_d2(void *);
void rlx_p5_mc_d0(void *);
void rlx_p5_mc_d1(void *);
void rlx_p5_mr_d0(void *);
void rlx_p5_mr_d1(void *);
void rlx_p5_ds_d0(void *);
void rlx_p5_ds_d1(void *);
void rlx_p5_st_p(void *);
void rlx_p5_hl_ctl(void *);

extern const struct p5_row p5_rows[P5_ROWS];
extern const char *const p5_names[P5_ROWS];

#endif
