/* probe6rows.c -- GENERATED by tools/tcpay.py.  DO NOT EDIT.
 *
 * A separate translation unit rather than an include, so that nothing in
 * the build holds two definitions of the row table -- probe5's rule.
 */
#include "probe6rows.h"

void rlxp6_c_lock(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_c_open(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v1(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v2(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v3(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v4(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v5(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v6(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v7(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v8(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v9(volatile unsigned *d, volatile const unsigned *s, unsigned sent);
void rlxp6_v10(volatile unsigned *d, volatile const unsigned *s, unsigned sent);

const char *const p6_names[P6_ROWS] = {
	"c_lock",
	"c_open",
	"v1",
	"v2",
	"v3",
	"v4",
	"v5",
	"v6",
	"v7",
	"v8",
	"v9",
	"v10",
};

const p6_thunk p6_thunks[P6_ROWS] = {
	rlxp6_c_lock,
	rlxp6_c_open,
	rlxp6_v1,
	rlxp6_v2,
	rlxp6_v3,
	rlxp6_v4,
	rlxp6_v5,
	rlxp6_v6,
	rlxp6_v7,
	rlxp6_v8,
	rlxp6_v9,
	rlxp6_v10,
};
