/* probe4rows.h -- GENERATED by tools/isapay.py from tools/isa-payload.tsv.
 * DO NOT EDIT.  See cells4.S.
 */
#ifndef PROBE4ROWS_H
#define PROBE4ROWS_H

#define P4_ROWS		75u
#define P4_ROW_WORDS	8u
#define P4_TAG_BASE	0x52340000u
#define P4_SCRATCH_B	48u

struct p4_row {
	void (*cell)(void *);
	unsigned int in_a;
	unsigned int in_b;
	unsigned int mem0;
	unsigned int mem1;
	unsigned int seed;
};

void rlx_p4_add(void *);
void rlx_p4_lw(void *);
void rlx_p4_sw(void *);
void rlx_p4_mult(void *);
void rlx_p4_mult_hi(void *);
void rlx_p4_beq(void *);
void rlx_p4_jr(void *);
void rlx_p4_special0e(void *);
void rlx_p4_lwl(void *);
void rlx_p4_lwr(void *);
void rlx_p4_swl(void *);
void rlx_p4_swr(void *);
void rlx_p4_ll(void *);
void rlx_p4_sc(void *);
void rlx_p4_clz(void *);
void rlx_p4_clo(void *);
void rlx_p4_mul(void *);
void rlx_p4_madd(void *);
void rlx_p4_madd_hi(void *);
void rlx_p4_movz(void *);
void rlx_p4_movn(void *);
void rlx_p4_sync(void *);
void rlx_p4_pref(void *);
void rlx_p4_ext(void *);
void rlx_p4_ins(void *);
void rlx_p4_rotr(void *);
void rlx_p4_seb(void *);
void rlx_p4_wsbh(void *);
void rlx_p4_synci(void *);
void rlx_p4_rdhwr(void *);
void rlx_p4_mfc1(void *);
void rlx_p4_lwc1(void *);
void rlx_p4_swc1(void *);
void rlx_p4_ldc1(void *);
void rlx_p4_sdc1(void *);
void rlx_p4_mfc3(void *);
void rlx_p4_mtc3(void *);
void rlx_p4_cfc3(void *);
void rlx_p4_lwc3(void *);
void rlx_p4_swc3(void *);
void rlx_p4_mflxc0(void *);
void rlx_p4_beql(void *);
void rlx_p4_bnel(void *);
void rlx_p4_blezl(void *);
void rlx_p4_bgtzl(void *);
void rlx_p4_cache10(void *);
void rlx_p4_cache11(void *);
void rlx_p4_cache15(void *);
void rlx_p4_cache19(void *);
void rlx_p4_mfc2(void *);
void rlx_p4_teq(void *);
void rlx_p4_tne(void *);
void rlx_p4_tge(void *);
void rlx_p4_tgeu(void *);
void rlx_p4_tlt(void *);
void rlx_p4_tltu(void *);
void rlx_p4_madh(void *);
void rlx_p4_madl(void *);
void rlx_p4_mazh(void *);
void rlx_p4_mazl(void *);
void rlx_p4_msbh(void *);
void rlx_p4_msbl(void *);
void rlx_p4_mszh(void *);
void rlx_p4_mszl(void *);
void rlx_p4_ltw(void *);
void rlx_p4_udi0i(void *);
void rlx_p4_udi1i(void *);
void rlx_p4_udi2i(void *);
void rlx_p4_udi3i(void *);
void rlx_p4_udi0(void *);
void rlx_p4_udi1(void *);
void rlx_p4_udi2(void *);
void rlx_p4_udi3(void *);
void rlx_p4_udi4(void *);
void rlx_p4_udi5(void *);

static const struct p4_row p4_rows[P4_ROWS] = {
	{ rlx_p4_add, 0x12345678u, 0x11111111u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_lw, 0x12345678u, 0x11111111u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_sw, 0x12345678u, 0x5A5A0FF2u, 0xA5A5F00Du, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mult, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mult_hi, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_beq, 0x0000002Au, 0x0000002Au, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_jr, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_special0e, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_lwl, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0x11223344u },
	{ rlx_p4_lwr, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0x11223344u },
	{ rlx_p4_swl, 0x00000000u, 0x5A5A0FF2u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_swr, 0x00000000u, 0x5A5A0FF2u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_ll, 0x00000000u, 0x00000000u, 0x0000A5F0u, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_sc, 0x00000000u, 0x5A5A0FF2u, 0xA5A5F00Du, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_clz, 0x00F00000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_clo, 0xFF000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mul, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_madd, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_madd_hi, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_movz, 0x0000002Au, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_movn, 0x0000002Au, 0x00000001u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_sync, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_pref, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_ext, 0x12345678u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_ins, 0x12345678u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_rotr, 0x00000000u, 0x12345678u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_seb, 0x00000000u, 0x123456F0u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_wsbh, 0x00000000u, 0x12345678u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_synci, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_rdhwr, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mfc1, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_lwc1, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_swc1, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_ldc1, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_sdc1, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mfc3, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mtc3, 0x00000000u, 0x5A5A0FF2u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_cfc3, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_lwc3, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_swc3, 0x00000000u, 0x5A5A0FF2u, 0xA5A5F00Du, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mflxc0, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_beql, 0x0000002Au, 0x0000002Au, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_bnel, 0x0000002Au, 0x0000002Bu, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_blezl, 0xFFFFFFFFu, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_bgtzl, 0x0000002Au, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_cache10, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_cache11, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_cache15, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_cache19, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_mfc2, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_teq, 0x0000002Au, 0x0000002Au, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_tne, 0x0000002Au, 0x0000002Bu, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_tge, 0x0000002Bu, 0x0000002Au, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_tgeu, 0x0000002Bu, 0x0000002Au, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_tlt, 0x0000002Au, 0x0000002Bu, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_tltu, 0x0000002Au, 0x0000002Bu, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_madh, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_madl, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mazh, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mazl, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_msbh, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_msbl, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mszh, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_mszl, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_ltw, 0x00000000u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p4_udi0i, 0x12345678u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi1i, 0x12345678u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi2i, 0x12345678u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi3i, 0x12345678u, 0x00000000u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi0, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi1, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi2, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi3, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi4, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
	{ rlx_p4_udi5, 0x12345678u, 0x00000010u, 0x00000000u, 0x00000000u, 0xDEADBEEFu },
};

/* Row names, for the banner.  One string per row, same order. */
static const char *const p4_names[P4_ROWS] = {
	"add",
	"lw",
	"sw",
	"mult",
	"mult_hi",
	"beq",
	"jr",
	"special0e",
	"lwl",
	"lwr",
	"swl",
	"swr",
	"ll",
	"sc",
	"clz",
	"clo",
	"mul",
	"madd",
	"madd_hi",
	"movz",
	"movn",
	"sync",
	"pref",
	"ext",
	"ins",
	"rotr",
	"seb",
	"wsbh",
	"synci",
	"rdhwr",
	"mfc1",
	"lwc1",
	"swc1",
	"ldc1",
	"sdc1",
	"mfc3",
	"mtc3",
	"cfc3",
	"lwc3",
	"swc3",
	"mflxc0",
	"beql",
	"bnel",
	"blezl",
	"bgtzl",
	"cache10",
	"cache11",
	"cache15",
	"cache19",
	"mfc2",
	"teq",
	"tne",
	"tge",
	"tgeu",
	"tlt",
	"tltu",
	"madh",
	"madl",
	"mazh",
	"mazl",
	"msbh",
	"msbl",
	"mszh",
	"mszl",
	"ltw",
	"udi0i",
	"udi1i",
	"udi2i",
	"udi3i",
	"udi0",
	"udi1",
	"udi2",
	"udi3",
	"udi4",
	"udi5",
};

#endif /* PROBE4ROWS_H */
