/* probe5rows.c -- GENERATED by tools/hazpay.py from
 * tools/isa-hazard.tsv.  DO NOT EDIT.
 *
 * The operands are here and the EXPECTATIONS ARE NOT: `hazpay.py
 * verdict` holds those at the desk, so there is nothing in the
 * image for a wrong expectation to be silently right against.
 */
#include "rlxprobe.h"
#include "probe5rows.h"

const struct p5_row p5_rows[P5_ROWS] = {
	{ rlx_p5_lu_alu_d0, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_lu_alu_d1, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_lu_alu_d2, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_lu_sd_d0, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_lu_sd_d1, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_sb_m0_d0, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_sb_m1_d0, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_sb_m0_d1, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_sb_m1_d1, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_hl_d0, 0x12345678u, 0x00000010u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_hl_d1, 0x12345678u, 0x00000010u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_hl_d2, 0x12345678u, 0x00000010u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_hl_d3, 0x12345678u, 0x00000010u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_c0_d0, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_c0_d1, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_c0_d2, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_mc_d0, 0x12345678u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_mc_d1, 0x12345678u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_mr_d0, 0x12345678u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_mr_d1, 0x12345678u, 0x00000000u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_ds_d0, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_ds_d1, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_st_p, 0x12345678u, 0xB10CB10Cu, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
	{ rlx_p5_hl_ctl, 0x12345678u, 0x00000010u, 0xA5A5F00Du, 0x5A5A0FF2u, 0xDEADBEEFu },
};

const char *const p5_names[P5_ROWS] = {
	"lu_alu_d0",
	"lu_alu_d1",
	"lu_alu_d2",
	"lu_sd_d0",
	"lu_sd_d1",
	"sb_m0_d0",
	"sb_m1_d0",
	"sb_m0_d1",
	"sb_m1_d1",
	"hl_d0",
	"hl_d1",
	"hl_d2",
	"hl_d3",
	"c0_d0",
	"c0_d1",
	"c0_d2",
	"mc_d0",
	"mc_d1",
	"mr_d0",
	"mr_d1",
	"ds_d0",
	"ds_d1",
	"st_p",
	"hl_ctl",
};
